### ISSUE TITLE
Syntax highlighting flickers while neotags is running

### ISSUE THREAD

**Issue by haasn** [c0r73x/neotags.nvim#13]
After opening a buffer, all of the highlighted type names etc. end up flickering back and forth between the chosen highlight color and the normal highlighting while neotags is recomputing the highlighting rules.

It flickers back and forth a good 5-10 times or so, and is quite distracting.

**Comment by c0r73x** [comment]
This happends because you for example have a class named `foo`, and a constructor for `foo`. Then it will first highlight it as a function, then as a class. The order is based on the g:neotags#[language]#order, i haven't found a better way to solve this, but pull requests are welcome.

**Comment by c0r73x** [comment]
Now it should flicker alot less.

**Comment by haasn** [comment]
Confirmed. With the new update, it no longer flickers; just incrementally (slowly) loads the colors in-place. Still not entirely sure why it takes absolutely forever to do so, but at least it's better than the old status quo.

**Comment by c0r73x** [comment]
The slow load was because of some debug stuff. I've fixed that in the latest commit.
