### ISSUE TITLE
Link the highlighted tag names to sensible values by default

### ISSUE THREAD

**Issue by haasn** [c0r73x/neotags.nvim#14]
`cTypeTag` etc. are all completely undefined by default, which sort of defeats the purpose of a highlighting engine. (And no, I don't plan on adding this boilerplate for every language in existence to my own .vimrc)

IMO the default should be linked to sane values like `cTypeTag` -> `Type`, `cFunctionTag` -> `Function` etc..

**Comment by c0r73x** [comment]
Done :)
