### ISSUE TITLE
Also highlight enum memebers for C etc.

### ISSUE THREAD

**Issue by haasn** [c0r73x/neotags.nvim#15]
The current highlight rules are rather limiting, compared to what kind of information ctags can actually detect. This file, from TagHighlight.vim (which is what I was using previously until it stopped working) provides a much more complete list:

https://github.com/vim-scripts/TagHighlight/blob/9ee760281ab6e8443ea9bb9ae484b0233b3f0e29/plugin/TagHighlight/data/kinds.txt

It would be great if you could add at least a couple of these to neotags as well.

**Comment by c0r73x** [comment]
For C/C++ all ctags members are now loaded. see the README for more information.
