### ISSUE TITLE
Clarity for ag use in readme.md

### ISSUE THREAD

**Issue by bearcatsandor** [c0r73x/neotags.nvim#16]
The way the following is written is unclear to me:

> To use the_silver_searcher or similar applications when generating tags you can do something like this.
> 
> let g:neotags_appendpath = 0
> let g:neotags_recursive = 0
> 
> " Use this option for the_silver_searcher
> let g:neotags_ctags_bin = 'ag -g "" '. getcwd() .' | ctags'
> " Or this one for ripgrep. Not both.
> let g:neotags_ctags_bin = 'rg --files '. getcwd() .' | ctags'
> let g:neotags_ctags_args = [
>             \ '-L -',
>             \ '--fields=+l',
>             \ '--c-kinds=+p',
>             \ '--c++-kinds=+p',
>             \ '--sort=no',
>             \ '--extras=+q'
>             \ ]

Is the ctags_args setting applicable to both the ag and the ripgrep setup?

**Comment by c0r73x** [comment]
Hi, yes all except the ctags_bin is for ripgrep or the_silver_searcher. I will change the readme to make it clearer.

**Comment by bearcatsandor** [comment]
Thank you
