### ISSUE TITLE
Difference with atags?

### ISSUE THREAD

**Issue by georgeteo** [c0r73x/neotags.nvim#2]
Hi, I stumbled across your project and was curious about how it differs from atags: https://github.com/fntlnz/atags.vim
I'm also trying to find async alternative to easytags.

**Comment by c0r73x** [comment]
Hi

Seems to me that atags.vim only generates tagfiles, neotags.nvim generates tags and highlights them similar to easytags but asynchronously.

However you can use both with g:neotags_run_ctags = 0. Then neotags.nvim will only highlight tags. And you can use atags.vim to generate the files.
