### ISSUE TITLE
`async=True` SyntaxError

### ISSUE THREAD

**Issue by amadanmath** [c0r73x/neotags.nvim#33]
Upon executing `:UpdateRemotePlugins`, this error appeared:

```
  File "/Users/amadan/.local/share/nvim/plugged/neotags.nvim/rplugin/python3/neotag
s/neotags.py", line 128
    self.vim.command('autocmd %s * call NeotagsUpdate()' % evupd, async=True)
                                                                      ^
SyntaxError: invalid syntax
```

I expect this is due to [`async`](https://docs.python.org/3/library/asyncio-task.html) being a keyword in Python since 3.7.0:

    import keyword
    keyword.iskeyword('async')
    # => True
    import sys
    sys.version
    # => '3.7.0 (default, Jun 29 2018, 20:13:13) \n[Clang 9.1.0 (clang-902.0.39.2)]'

**Comment by roflcopter4** [comment]
That would be the problem. Should be fixed now.
