### ISSUE TITLE
"E117: Unknown Function: NeotagsInit" on installing with vim-plug

### ISSUE THREAD

**Issue by tesseract241** [c0r73x/neotags.nvim#42]
I have installed the requirements (psutils, neovim python client, universal c-tags) but I'm stuck with this error.  
I'm on Linux Mint 64 bit.

**Comment by c0r73x** [comment]
You have to run :UpdateRemotePlugins

Skickat från min iPhone

**Comment by tesseract241** [comment]
Solved.
Maybe add both :UpdateRemotePlugins and installing universal-ctags to the installation steps in the project's README?
