### ISSUE TITLE
Disable/enable tags highlighting on the fly

### ISSUE THREAD

**Issue by dominikduda** [c0r73x/neotags.nvim#6]
Hello,

Would it be possible to enable/disable tags highlighting without restarting nvim? Tag highlighting is awesome but it makes vim deadly slow, I'd love to just enable it when i need.

Or maybe it can be done already?

**Comment by c0r73x** [comment]
For the moment you can't clear the highlight. I will check if I can implement a toggle function.

**Comment by c0r73x** [comment]
I've added the NeotagsToggle command :)

**Comment by dominikduda** [comment]
I completly removed and again installed the plugin and I am getting this error message when calling `:NeotagsToggle`
![image](https://cloud.githubusercontent.com/assets/14922999/22061150/fc0538fa-dd73-11e6-8c78-b0f95cd7ec02.png)

**Comment by c0r73x** [comment]
Did you run :UpdateRemotePlugins ?

**Comment by dominikduda** [comment]
After running `:UpdateRemotePlugins` it works. Thank you very much for your time and effort. :)

**Comment by c0r73x** [comment]
Awesome 🍻
