### ISSUE TITLE
Neotags fails to start when installed with vim-plug

### ISSUE THREAD

**Issue by 3goliad** [c0r73x/neotags.nvim#7]
I have the python3 neovim and psutils packages installed, and I have installed Neotags using vim-plug. On vim startup, I get the message
`Error detected while processing VimEnter Auto commands for "*":                                  
E117: Unknown function: NeotagsInit`
Would you happen to know what might be tripping vim up?

**Comment by c0r73x** [comment]
Hi, I use vim-plug myself. From the error it looks like you forgot to run :UpdateRemotePlugins.

I use this in my vimrc for neovim-plugins:
```viml
...
function! DoRemote(arg)
    UpdateRemotePlugins
endfunction

Plug 'c0r73x/neotags.nvim', { 'do': function('DoRemote') }
...
```

**Comment by 3goliad** [comment]
Thanks! My apologies.
